export const FAQS = [
  {
    question: "1. What is a kWh (Kilowatt-hour) or \"Unit\" of electricity?",
    answer: "In utility billing, 1 'unit' of electricity is exactly equal to 1 kWh (Kilowatt-Hour). This measures the total quantity of energy consumed. If a 1,000-Watt (1 kW) appliance runs continuously for 1 hour, it consumes exactly 1 unit (1 kWh) of electricity."
  },
  {
    question: "2. What is 1 kW load?",
    answer: "A 1 kW load represents a simultaneous power draw of 1,000 Watts at any single moment. It is a measure of instantaneous demand. For example, running a 1,000W electric iron or ten 100W bulbs at the exact same time creates a 1 kW load on your home's electrical system."
  },
  {
    question: "3. How do I calculate my electricity load?",
    answer: "List all electrical appliances you intend to run at the same time, find their wattage ratings (usually printed on a label on the back), multiply by quantity, and add them up. Divide the total watts by 1,000 to get your active load in kW. For example, a 1,500W AC and a 500W Refrigerator running together create a 2,000W (or 2 kW) load."
  },
  {
    question: "4. How much unit does 3000 watts consume in 1 hour?",
    answer: "A 3,000-Watt load is equal to 3 kW of power demand. Running this load for 1 hour consumes exactly 3 units (or 3 kWh) of electricity. Formula: (3,000 Watts × 1 Hour) / 1,000 = 3 kWh (Units)."
  },
  {
    question: "5. What is the load capacity of a 5 kW meter?",
    answer: "A 5 kW meter is designed to support a maximum simultaneous demand of 5,000 Watts. This allows you to run multiple heavy appliances together—such as a 1.5 kW AC, a 2 kW water geyser, and 1.5 kW of lights and fans—as long as their combined wattage at any single moment stays below 5 kW."
  },
  {
    question: "6. How do I choose the correct wire (cable) and MCB size for my load?",
    answer: "Determine your load current by dividing its watts by voltage (Amps = Watts / 230V). Following electrical safety codes, size your breaker to be 125% of this current draw (e.g., 15A current requires a 20A MCB). Choose a copper wire cross-section (in sq mm) rated to handle more current than the MCB to prevent wire overheating."
  },
  {
    question: "7. How do I determine the right size for a home Inverter and battery backup?",
    answer: "Sum the wattages of all essential appliances you need during a power cut (e.g., lights, fans, router). Size your Inverter capacity (in kVA) to be 20% to 30% higher than this peak simultaneous load. Select your battery capacity (in Ah) based on the number of backup hours you require."
  },
  {
    question: "8. How do I calculate the solar panel capacity needed to offset my electricity units?",
    answer: "Check your monthly utility bill for your average monthly unit consumption in kWh. Divide this monthly consumption by 120 (the average monthly units generated by 1 kW of solar panels in standard climates). For example, consuming 600 units a month requires a 5 kW solar panel array (600 / 120 = 5 kW) to bring your grid bill to zero."
  },
  {
    question: "9. What runs up your electricity bill the most at home?",
    answer: "The largest contributors to high utility bills are cooling and heating appliances. Air Conditioners, Water Geysers, Space Heaters, and old double-door Refrigerators (which run 24/7) consume over 75% of your home's total electricity. Switch-level standby leaks (phantom load) account for another 5–10%."
  },
  {
    question: "10. How many watts does a 1.5 Ton AC consume, and how many units does it use?",
    answer: "A typical 1.5 Ton air conditioner consumes between 1,200W and 1,800W. A modern 5-star inverter AC runs at around 1,200 Watts. If run for 8 hours daily: (1,200W × 1 AC × 8 Hours) / 1,000 = 9.6 kWh (units) consumed per day, or roughly 288 units per month."
  },
  {
    question: "11. Do I need a single-phase or three-phase meter connection for my house?",
    answer: "Single-phase meters (230V) are standard for connected loads under 5 kW to 7 kW (typical for small apartments/homes). If your calculated load exceeds 7 kW (e.g., you have multiple ACs, a water pump, and induction cooktops running at once), you must upgrade to a three-phase meter (415V) to distribute the load evenly."
  },
  {
    question: "12. How do I convert electrical current (Amps) back to power load (kW)?",
    answer: "For a standard single-phase residential supply (230V), use the formula: Watts = Amps × 230. To get kW, divide the result by 1,000. For example, if your appliance draws 16 Amps: 16 × 230 = 3,680W, which is equal to 3.68 kW of instantaneous load."
  }
];
